# Generated by Django 5.2.8 on 2025-11-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceuser',
            name='role',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=6),
        ),
    ]
