# Generated by Django 5.2.8 on 2025-11-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_freelanceuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
