# Generated by Django 5.2.8 on 2025-12-05 11:52

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_freelanceuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceuser',
            name='country',
            field=models.CharField(default='Russian', verbose_name='County'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelanceuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 32 characters or less to 4. Letters, digits only.', max_length=32, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(4)], verbose_name='username'),
        ),
    ]
