# Generated by Django 5.2.8 on 2025-12-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_freelanceuser_country_alter_freelanceuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceuser',
            name='country',
            field=models.CharField(verbose_name='Country'),
        ),
    ]
