# Generated by Django 5.2.8 on 2025-11-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruser',
            name='orders_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
