# Generated by Django 5.2.8 on 2025-11-28 16:57

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_selleruser_negative_reviews_selleruser_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleruser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_directory_path),
        ),
    ]
