# Generated by Django 5.2.8 on 2025-11-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_selleruser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='is_positive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
