# Generated by Django 5.2.8 on 2025-11-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_review_rating_review_is_positive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleruser',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.selleruser'),
            preserve_default=False,
        ),
    ]
