# Generated by Django 5.2.8 on 2025-11-29 18:55

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_selleruser_reviews_review_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='selleruser',
            options={'verbose_name': 'Seller User Profile', 'verbose_name_plural': 'Seller User Profiles'},
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Review Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Review Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_positive',
            field=models.BooleanField(verbose_name='Is Positive Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.selleruser', verbose_name='Reviewed Seller'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_directory_path, verbose_name='Avatar user image'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description about seller'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='negative_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of negative reviews'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Total number of orders'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='orders_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of completed orders'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='positive_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of positive reviews'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Seller rating'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='reviews_all',
            field=models.PositiveIntegerField(default=0, verbose_name='Total number of reviews'),
        ),
    ]
