# Generated by Django 5.2.8 on 2025-11-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_review_options_alter_selleruser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleruser',
            name='rating',
        ),
    ]
