# Generated by Django 5.2.8 on 2025-12-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_buyeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeruser',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Description about buyer'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Description about seller'),
        ),
    ]
