# Generated by Django 5.2.8 on 2025-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_buyeruser_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeruser',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
    ]
